const app = new Vue({
  el: "#app",
  data: {
    products: [
      {
        title: "HigaCoffee Database",
        year: "2020/8-",
        description: "",
        langs: ["Nuxt.js", "Flask", "Firebase"],
        isTeam: true,
        imageSrc: "",
        githubSrc: "",
        link: "",
      },
      {
        title: "Hobeeeeee!!",
        year: "2020/10-2021/1",
        description: "",
        langs: ["Nuxt.js", "Firebase"],
        isTeam: true,
        imageSrc: "",
        githubSrc: "https://github.com/enpitut2020/Hobeeeeee",
        link: "",
      },
      {
        title: "ぷろぐらみんぐうぃっち",
        year: "2020/12-2021/1",
        description: "",
        langs: ["Unity", "Firebase"],
        isTeam: true,
        imageSrc: "",
        githubSrc: "",
        link: "",
      },
      {
        title: "ほんとも",
        year: "2020/9",
        description: "",
        langs: ["Vue.js", "Firebase"],
        isTeam: true,
        imageSrc: "",
        githubSrc: "",
        link: "hontomo-pre.netlify.app",
      },
      {
        title: "PocketMentor",
        year: "2020/7",
        description: "",
        langs: ["Ruby", "Docker"],
        isTeam: true,
        imageSrc: "",
        githubSrc: "",
        link: "",
      },
      {
        title: "RefriSuggester",
        year: "2020/7",
        description: "授業のハッカソンで制作。「冷蔵庫にあるもので作れるものを知りたい」がコンセプトのLINEボット。<br/>企画・データ取得・メッセージ整形などを担当",
        langs: ["Sinatra", "Firebase", "Elasticsearch"],
        isTeam: true,
        imageSrc: "",
        githubSrc: "https://github.com/twice-cooked-pork/chat-bot-server",
        link: "",
      },
      {
        title: "ShareTsukuba",
        year: "2020/6",
        description: "Railsチュートリアルに沿いながら、Docker上で動作するオリジナルのアプリケーションを作成した。",
        langs: ["Rails", "Docker"],
        isTeam: false,
        imageSrc: "",
        githubSrc: "https://github.com/Hotsukai/share_tsukuba",
        link: "",
      },
      {
        title: "宿舎祭公式サイト",
        year: "2020/3-2020/4",
        description:
          "筑波大学宿舎祭(やどかり祭)の広報のため制作。PM・コーダーを担当",
        langs: ["HTML", "CSS", "jQuery"],
        isTeam: true,
        imageSrc: "/images/yado.png",
        githubSrc: "",
        link: "",
      },
    ],
  },
});
