const app = new Vue({
  el: "#app",
  data: {
    products: [
      {
        title: "HigaCoffee Database",
        year: "2020/8-",
        description: "",
        langs: ["Nuxt.js", "Flask", "Firebase"],
        isTeam: true,
        imageSrc: "images/higa.png",
        github: "https://github.com/Hotsukai/HigaCoffeeDBFront",
        link: "https://higa-database.netlify.app/",
      },
      {
        title: "Hobeeeeee!!",
        year: "2020/10-2021/1",
        description: "",
        langs: ["Nuxt.js", "Firebase"],
        isTeam: true,
        imageSrc: "images/hobeeeeee.png",
        github: "https://github.com/enpitut2020/Hobeeeeee",
        link: "https://hobeeeeee.netlify.app/",
      },
      {
        title: "ぷろぐらみんぐうぃっち",
        year: "2020/12-2021/1",
        description: "小学校でプログラミングが必修化されるがスキルを定量化できるかに疑問を持ち、小学生向けの競技プログラミングをテーマに制作。<br>ランキングや問題取得などバックエンドとの通信部分を担当した。",
        langs: ["Unity", "Firebase"],
        isTeam: true,
        imageSrc: "images/programmingWitch.png",
        github: "",
        link: "",
      },
      {
        title: "ほんとも",
        year: "2020/9",
        description: "",
        langs: ["Vue.js", "Firebase"],
        isTeam: true,
        imageSrc: "",
        github: "",
        link: "https://hontomo-pre.netlify.app",
      },
      {
        title: "PocketMentor",
        year: "2020/7",
        description: "",
        langs: ["Ruby", "Docker"],
        isTeam: true,
        imageSrc: "",
        github: "",
        link: "",
      },
      {
        title: "RefriSuggester",
        year: "2020/7",
        description: "授業のハッカソンで制作。「冷蔵庫にあるもので作れるものを知りたい」がコンセプトのLINEボット。<br/>企画・データ取得・メッセージ整形などを担当",
        langs: ["Sinatra", "Firebase", "Elasticsearch"],
        isTeam: true,
        imageSrc: "",
        github: "https://github.com/twice-cooked-pork/chat-bot-server",
        link: "",
      },
      {
        title: "ShareTsukuba",
        year: "2020/6",
        description: "Railsチュートリアルに沿いながら、Docker上で動作するオリジナルのアプリケーションを作成した。",
        langs: ["Rails", "Docker"],
        isTeam: false,
        imageSrc: "images/shareTsukuba.png",
        github: "https://github.com/Hotsukai/share_tsukuba",
        link: "https://share-tsukuba.herokuapp.com/",
      },
      {
        title: "宿舎祭公式サイト",
        year: "2020/3-2020/4",
        description:
          "筑波大学宿舎祭(やどかり祭)の広報のため制作。PM・コーダーを担当",
        langs: ["HTML", "CSS", "jQuery"],
        isTeam: true,
        imageSrc: "/images/yado.png",
        github: "",
        link: "https://www.yadosai.com/",
      },
    ],
  },
});
